version: "3.8"
services:
    cli-folder-organiser:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        command: npm start
        volumes:
            - .:/cli-folder-organiser
